---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-rds-access
  namespace: mlflow
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725490567891:role/eks-mlflow-s3-rds-access-role