apiVersion: v1
kind: Namespace
metadata:
  name: ml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725490567891:role/eks-ml-s3-access-role
